// Code generated by goctl. DO NOT EDIT.

export interface CreateRecordReq {
	profileName: string
	reference: string
}

export interface CreateRecordResp {
	code: number
	recordId: number
	msg: string
}

export interface DeleteRecordReq {
	profileName: string
	recordId: number
}

export interface DeleteRecordResp {
	code: number
	msg: string
}

export interface FileDetails {
	presignedurl: string
	fileName: string
}

export interface GetAudioUrlReq {
	profileName: string
	recordId: number
}

export interface GetAudioUrlResp {
	code: number
	data: FileDetails
	msg: string
}

export interface GetPerformanceAudioReq {
	profileName: string
	recordId: number
}

export interface GetPerformanceAudioResp {
	code: number
	presignedurl: string
	msg: string
}

export interface GetPerformanceImgReq {
	profileName: string
	recordId: number
}

export interface GetPerformanceImgResp {
	code: number
	presignedurl: string
	msg: string
}

export interface GetPerformanceMidiReq {
	profileName: string
	recordId: number
}

export interface GetPerformanceMidiResp {
	code: number
	presignedurl: string
	msg: string
}

export interface GetPerformanceReportReq {
	profileName: string
	recordId: number
}

export interface GetPerformanceReportResp {
	code: number
	presignedurl: string
	msg: string
}

export interface GetPerformanceSheetReq {
	profileName: string
	recordId: number
}

export interface GetPerformanceSheetResp {
	code: number
	presignedurl: string
	msg: string
}

export interface GetPerformanceVideoReq {
	profileName: string
	recordId: number
}

export interface GetPerformanceVideoResp {
	code: number
	presignedurl: string
	msg: string
}

export interface GetPerformanceWaterfallReq {
	profileName: string
	recordId: number
}

export interface GetPerformanceWaterfallResp {
	code: number
	presignedurl: string
	msg: string
}

export interface GetRecordReq {
	profileName: string
	limit: number
	offset?: number
	start: number
	end: number
}

export interface GetRecordResp {
	code: number
	data: Array<RecordInfo>
	msg: string
}

export interface GetVideoUrlReq {
	profileName: string
	recordId: number
}

export interface GetVideoUrlResp {
	code: number
	data: FileDetails
	msg: string
}

export interface Record {
	subUserId: string
	timestamp: number
	composition: string
	reference: string
	image: string
	video: string
	audio: string
	midi: string
	sheet: string
	diff: string
	waterfall: string
	report: string
	isRef: boolean
}

export interface RecordInfo {
	RecordId: number
	composition: string
	reference: string
}

export interface SetAsReferenceReq {
	profileName: string
	recordId: number
	isRef: boolean
}

export interface SetAsReferenceResp {
	code: number
	msg: string
}

export interface UploadAudioSuccessReq {
	profileName: string
	recordId: number
	fileName: string
}

export interface UploadAudioSuccessResp {
	code: number
	profileName: string
	msg: string
}

export interface UploadVideoSuccessReq {
	profileName: string
	recordId: number
	fileName: string
}

export interface UploadVideoSuccessResp {
	code: number
	msg: string
}

export interface CreateReferenceReq {
	title: string
	style: string
	composer: string
	instrument: string
}

export interface CreateReferenceResp {
	code: number
	refId: string
	msg: string
}

export interface DeleteReferenceReq {
	refId: string
}

export interface DeleteReferenceResp {
	code: number
	msg: string
}

export interface GetAnalysisResultReq {
}
export interface GetAnalysisResultReqParams {
	analysisId: number
}

export interface GetAnalysisResultResp {
	code: number
	data: ResultData
	msg: string
}

export interface GetRefAudioReq {
	refId: string
}

export interface GetRefAudioResp {
	code: number
	presignedurl: string
	msg: string
}

export interface GetRefAudioUrlReq {
	refId: string
}

export interface GetRefAudioUrlResp {
	code: number
	data: UrlDetails
	msg: string
}

export interface GetRefImgReq {
	refId: string
}

export interface GetRefImgResp {
	code: number
	presignedurl: string
	msg: string
}

export interface GetRefImgUrlReq {
	refId: string
}

export interface GetRefImgUrlResp {
	code: number
	data: UrlDetails
	msg: string
}

export interface GetRefMidiReq {
	refId: string
}

export interface GetRefMidiResp {
	code: number
	presignedurl: string
	msg: string
}

export interface GetRefSheetReq {
	refId: string
}

export interface GetRefSheetResp {
	code: number
	presignedurl: string
	msg: string
}

export interface GetRefVideoReq {
	refId: string
}

export interface GetRefVideoResp {
	code: number
	presignedurl: string
	msg: string
}

export interface GetRefVideoUrlReq {
	refId: string
}

export interface GetRefVideoUrlResp {
	code: number
	data: UrlDetails
	msg: string
}

export interface GetRefWaterfallReq {
	refId: string
}

export interface GetRefWaterfallResp {
	code: number
	presignedurl: string
	msg: string
}

export interface GetReferenceReq {
	refId: string
}

export interface GetReferenceResp {
	code: number
	data: QueryResult
	msg: string
}

export interface PerformanceAnalysisReq {
	profileName: string
	recordId: number
}

export interface PerformanceAnalysisResp {
	code: number
	analysisId: number
	msg: string
}

export interface QueryReferenceReq {
	title: string
	style: string
	composer: string
	instrument: string
}

export interface QueryReferenceResp {
	code: number
	data: Array<QueryResult>
	msg: string
}

export interface QueryResult {
	refId: string
	title: string
	style: string
	composer: string
	instrument: string
}

export interface Reference {
	refId: string
	title: string
	style: string
	composer: string
	instrument: string
	image: string
	video: string
	audio: string
	midi: string
	sheet: string
	waterfall: string
	json: string
}

export interface ResultData {
	analysisRank: number
}

export interface UploadRefAudioSuccessReq {
	refId: string
	fileName: string
}

export interface UploadRefAudioSuccessResp {
	code: number
	msg: string
}

export interface UploadRefImgSuccessReq {
	refId: string
	fileName: string
}

export interface UploadRefImgSuccessResp {
	code: number
	msg: string
}

export interface UploadRefVideoSuccessReq {
	refId: string
	fileName: string
}

export interface UploadRefVideoSuccessResp {
	code: number
	msg: string
}

export interface UrlDetails {
	presignedurl: string
	fileName: string
}