// Code generated by goctl. DO NOT EDIT.

export interface CreateRecordReq {
	profileName: string
	reference: string
}

export interface CreateRecordResp {
	code: number
	recordId: number
	msg: string
}

export interface DeleteRecordReq {
	profileName: string
	recordId: number
}

export interface DeleteRecordResp {
	code: number
	msg: string
}

export interface FileDetails {
	presignedurl: string
	fileName: string
}

export interface GetAudioUrlReq {
	profileName: string
	recordId: number
}

export interface GetAudioUrlResp {
	code: number
	data: FileDetails
	msg: string
}

export interface GetPerformanceAudioReq {
	profileName: string
	recordId: number
}

export interface GetPerformanceAudioResp {
	code: number
	presignedurl: string
	msg: string
}

export interface GetPerformanceImgReq {
	profileName: string
	recordId: number
}

export interface GetPerformanceImgResp {
	code: number
	presignedurl: string
	msg: string
}

export interface GetPerformanceMidiReq {
	profileName: string
	recordId: number
}

export interface GetPerformanceMidiResp {
	code: number
	presignedurl: string
	msg: string
}

export interface GetPerformanceReportReq {
	profileName: string
	recordId: number
}

export interface GetPerformanceReportResp {
	code: number
	presignedurl: string
	msg: string
}

export interface GetPerformanceSheetReq {
	profileName: string
	recordId: number
}

export interface GetPerformanceSheetResp {
	code: number
	presignedurl: string
	msg: string
}

export interface GetPerformanceVideoReq {
	profileName: string
	recordId: number
}

export interface GetPerformanceVideoResp {
	code: number
	presignedurl: string
	msg: string
}

export interface GetPerformanceWaterfallReq {
	profileName: string
	recordId: number
}

export interface GetPerformanceWaterfallResp {
	code: number
	presignedurl: string
	msg: string
}

export interface GetRecordReq {
	profileName: string
	limit: number
	offset?: number
	start: number
	end: number
}

export interface GetRecordResp {
	code: number
	data: Array<RecordInfo>
	msg: string
}

export interface GetVideoUrlReq {
	profileName: string
	recordId: number
}

export interface GetVideoUrlResp {
	code: number
	data: FileDetails
	msg: string
}

export interface Record {
	subUserId: string
	timestamp: number
	composition: string
	reference: string
	image: string
	video: string
	audio: string
	midi: string
	sheet: string
	diff: string
	waterfall: string
	report: string
	isRef: boolean
}

export interface RecordInfo {
	RecordId: number
	composition: string
	reference: string
}

export interface SetAsReferenceReq {
	profileName: string
	recordId: number
	isRef: boolean
}

export interface SetAsReferenceResp {
	code: number
	msg: string
}

export interface UploadAudioSuccessReq {
	profileName: string
	recordId: number
	fileName: string
}

export interface UploadAudioSuccessResp {
	code: number
	profileName: string
	msg: string
}

export interface UploadVideoSuccessReq {
	profileName: string
	recordId: number
	fileName: string
}

export interface UploadVideoSuccessResp {
	code: number
	msg: string
}

