// Code generated by goctl. DO NOT EDIT.
package types

type CreateRecordReq struct {
	ProfileName string `json:"profileName"`
	Reference   string `json:"reference"`
}

type CreateRecordResp struct {
	Code     int64  `json:"code"`
	RecordId int64  `json:"recordId"`
	Msg      string `json:"msg"`
}

type DeleteRecordReq struct {
	ProfileName string `json:"profileName"`
	RecordId    int64  `json:"recordId"`
}

type DeleteRecordResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type FileDetails struct {
	PresignedURL string `json:"presignedurl"`
	FileName     string `json:"fileName"`
}

type GetAudioUrlReq struct {
	ProfileName string `json:"profileName"`
	RecordId    int64  `json:"recordId"`
}

type GetAudioUrlResp struct {
	Code int         `json:"code"`
	Data FileDetails `json:"data"`
	Msg  string      `json:"msg"`
}

type GetPerformanceAudioReq struct {
	ProfileName string `json:"profileName"`
	Pin         string `json:"pin"`
}

type GetPerformanceAudioResp struct {
	Code         int    `json:"code"`
	PresignedURL string `json:"presignedurl"`
	Msg          string `json:"msg"`
}

type GetPerformanceImgReq struct {
	ProfileName string `json:"profileName"`
	RecordId    int64  `json:"recordId"`
}

type GetPerformanceImgResp struct {
	Code         int    `json:"code"`
	PresignedURL string `json:"presignedurl"`
	Msg          string `json:"msg"`
}

type GetPerformanceMidiReq struct {
	ProfileName string `json:"profileName"`
	Pin         string `json:"pin"`
}

type GetPerformanceMidiResp struct {
	Code         int    `json:"code"`
	PresignedURL string `json:"presignedurl"`
	Msg          string `json:"msg"`
}

type GetPerformanceReportReq struct {
	ProfileName string `json:"profileName"`
	Pin         string `json:"pin"`
}

type GetPerformanceReportResp struct {
	Code         int    `json:"code"`
	PresignedURL string `json:"presignedurl"`
	Msg          string `json:"msg"`
}

type GetPerformanceSheetReq struct {
	ProfileName string `json:"profileName"`
	Pin         string `json:"pin"`
}

type GetPerformanceSheetResp struct {
	Code         int    `json:"code"`
	PresignedURL string `json:"presignedurl"`
	Msg          string `json:"msg"`
}

type GetPerformanceVedioReq struct {
	ProfileName string `json:"profileName"`
	RecordId    int64  `json:"recordId"`
}

type GetPerformanceVedioResp struct {
	Code         int    `json:"code"`
	PresignedURL string `json:"presignedurl"`
	Msg          string `json:"msg"`
}

type GetPerformanceWaterfallReq struct {
	ProfileName string `json:"profileName"`
	Pin         string `json:"pin"`
}

type GetPerformanceWaterfallResp struct {
	Code         int    `json:"code"`
	PresignedURL string `json:"presignedurl"`
	Msg          string `json:"msg"`
}

type GetRecordReq struct {
	ProfileName string `json:"profileName"`
	Limit       int    `json:"limit,optional"`
	Offset      int    `json:"offset,optional"`
	Start       string `json:"start,optional"`
	End         string `json:"end,optional"`
}

type GetRecordResp struct {
	Code int          `json:"code"`
	Data []RecordInfo `json:"data"`
	Msg  string       `json:"msg"`
}

type GetVedioUrlReq struct {
	ProfileName string `json:"profileName"`
	RecordId    int64  `json:"recordId"`
}

type GetVedioUrlResp struct {
	Code int         `json:"code"`
	Data FileDetails `json:"data"`
	Msg  string      `json:"msg"`
}

type Record struct {
	SubUserId   string `json:"subUserId"`
	Timestamp   int64  `json:"timestamp"`
	Composition string `json:"composition"`
	Reference   string `json:"reference"`
	Image       string `json:"image"`
	Video       string `json:"video"`
	Audio       string `json:"audio"`
	Midi        string `json:"midi"`
	Sheet       string `json:"sheet"`
	Diff        string `json:"diff"`
	Waterfall   string `json:"waterfall"`
	Report      string `json:"report"`
	IsRef       string `json:"isRef"`
}

type RecordInfo struct {
	RecordId    string `json:"profileName"`
	Composition string `json:"composition"`
	Reference   string `json:"reference"`
}

type SetAsReferenceReq struct {
	ProfileName string `json:"profileName"`
	RecordId    int64  `json:"recordId"`
}

type SetAsReferenceResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type UploadAudioSuccessReq struct {
	ProfileName string `json:"profileName"`
	RecordId    int64  `json:"recordId"`
	FileName    string `json:"fileName"`
}

type UploadAudioSuccessResp struct {
	Code        int    `json:"code"`
	ProfileName string `json:"profileName"`
	Msg         string `json:"msg"`
}

type UploadVideoSuccessReq struct {
	ProfileName string `json:"profileName"`
	RecordId    int64  `json:"recordId"`
	FileName    string `json:"fileName"`
}

type UploadVideoSuccessResp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}
