apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: audioanalysis
  name: audioanalysis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: audioanalysis
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: audioanalysis
    spec:
      containers:
        - args:
            - python
            - consumer.py
          image: audioanalysis
          name: audioanalysis
          volumeMounts:
            - mountPath: /app/audioanalysis
              name: audioanalysis-cm0
          workingDir: /app/audioanalysis
      restartPolicy: Always
      volumes:
        - configMap:
            name: audioanalysis-cm0
          name: audioanalysis-cm0
