version: '3.8'

services:
  usercenter:
    build:
      context: .
      dockerfile: app/usercenter/Dockerfile
    ports:
      - "8888:8888"


  media:
    build:
      context: .
      dockerfile: app/media/Dockerfile
    ports:
      - "8889:8889"

