apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  type: NodePort
  ports:
    - name: "4396"
      port: 4396
      targetPort: 80
      nodePort: 30001
  selector:
    io.kompose.service: nginx
