// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	user "github.com/cedarHH/mygo/app/usercenter/api/internal/handler/user"
	"github.com/cedarHH/mygo/app/usercenter/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// login
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				// register
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: user.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/usercenter/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// get user auth by user id
				Method:  http.MethodPost,
				Path:    "/user/auth/id",
				Handler: user.GetUserAuthByUserIdHandler(serverCtx),
			},
			{
				// get user auth by auth key
				Method:  http.MethodPost,
				Path:    "/user/auth/key",
				Handler: user.GetUserAuthByAuthKeyHandler(serverCtx),
			},
			{
				// get user info
				Method:  http.MethodPost,
				Path:    "/user/info",
				Handler: user.GetUserInfoHandler(serverCtx),
			},
			{
				// generate token
				Method:  http.MethodPost,
				Path:    "/user/token",
				Handler: user.GenerateTokenHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/usercenter/v1"),
	)
}
