# This workflow is automatically forward integrated into the backend and frontend

name: Auto Forward Integrate Develop to Backend and Frontend

on:
  push:
    branches:
      - develop

jobs:
  forward-integrate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: develop

    - name: Set up Git user
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Merge develop into backend
      run: |
        git checkout backend
        git merge develop
        git push origin backend

    - name: Merge develop into frontend
      run: |
        git checkout frontend
        git merge develop
        git push origin frontend
