# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main", "develop", "release/*" ]
  pull_request:
    branches: [ "main", "develop", "release/*" ]

jobs:

  prevent-direct-push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
    - name: Prevent direct push to main and release branches
      run: |
        protected_branches_regex='^main$|^release/.*$'
        if [[ $GITHUB_REF =~ $protected_branches_regex ]]; then
          echo "Direct pushes to 'main' and 'release/*' branches are not allowed."
          exit 1
        fi

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v ./backend/...

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.58
        args: ./backend/...

    - name: Run Gosec Security Scanner
      uses: securego/gosec@master
      with:
        args: ./backend/...

    - name: Test
      run: go test -v ./backend/...
