# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go CI

on:
  push:
    branches: [ 'backend/**' ]
  pull_request:
    branches: [ "main", "develop", "release/*", 'backend/**' ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v ./backend/...

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.58
        args: ./backend/...

    - name: Run Gosec Security Scanner
      uses: securego/gosec@master
      with:
        args: ./backend/...

    - name: Test
      run: go test -v ./backend/...
