// Code generated by goctl. DO NOT EDIT.
package types

type GenerateTokenReq struct {
	UserId int64 `json:"userId"`
}

type GenerateTokenResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type GetUserAuthByAuthKeyReq struct {
	AuthKey  string `json:"authKey"`
	AuthType string `json:"authType"`
}

type GetUserAuthByAuthKeyResp struct {
	UserAuth UserAuth `json:"userAuth"`
}

type GetUserAuthByUserIdReq struct {
	UserId   int64  `json:"userId"`
	AuthType string `json:"authType"`
}

type GetUserAuthByUserIdResp struct {
	UserAuth UserAuth `json:"userAuth"`
}

type GetUserInfoReq struct {
	Id int64 `json:"id"`
}

type GetUserInfoResp struct {
	UserInfo User `json:"userInfo"`
}

type LoginReq struct {
	AuthType string `json:"authType"`
	AuthKey  string `json:"authKey"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type RegisterReq struct {
	Mobile   string `json:"mobile"`
	Nickname string `json:"nickname"`
	Password string `json:"password"`
	AuthKey  string `json:"authKey"`
	AuthType string `json:"authType"`
}

type RegisterResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type User struct {
	Id       int64  `json:"id"`
	Mobile   string `json:"email"`
	Nickname string `json:"nickname"`
	Sex      int64  `json:"sex"`
	Avatar   string `json:"avatar"`
	Info     string `json:"info"`
}

type UserAuth struct {
	Id       int64  `json:"id"`
	UserId   int64  `json:"userId"`
	AuthType string `json:"authType"`
	AuthKey  string `json:"authKey"`
}
